name: create vpc demo
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: My input description
        required: false
        type: string
jobs:
  create-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create VPC
        run: |
          aws ec2 create-vpc --cidr-block 10.0.0.0/16
          
      - name: List all files
        run: ls -lR
