name: update vpc template

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: My input description
        required: false
        type: string

jobs:
  create-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update CloudFormation Stack
        run: aws cloudformation update-stack --stack-name subnet-vpc --template-body file://cloudformation/template.yaml --capabilities CAPABILITY_IAM

      - name: Wait for Stack Update
        run: aws cloudformation wait stack-update-complete --stack-name subnet-vpc

      - name: Describe Stack Events
        run: aws cloudformation describe-stack-events --stack-name subnet-vpc
