AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates VPC in us-east-1 region
  Author: Sadiya
  Company: test

Resources:
  MyCfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: MyVPC
        - Key: Env
          Value: Prod
        - Key: Department
          Value: DevOps

  MyCfnInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyIGW

  MyCfnAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-0522b23e14b1638de
      InternetGatewayId: igw-0124fbcbe44575b79

  MyCfnPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0522b23e14b1638de
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet  

  MyCfnPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0522b23e14b1638de
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: PrivateSubnet

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: vpc-0522b23e14b1638de
      Tags: 
        - Key: Name
          Value: PublicRouteTable

  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: vpc-0522b23e14b1638de
      Tags: 
        - Key: Name
          Value: PrivateRouteTable 

  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: rtb-006a9f9de6bff6813
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: igw-0124fbcbe44575b79 

  NatGatewayEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc 
  
  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: 
        Fn::GetAtt: 
          - NatGatewayEIP
          - AllocationId
      SubnetId: subnet-0ea8fbfbc1309cb64
      Tags: 
        - Key: Name
          Value: MyNATGateway

   PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: rtb-0b4f0ecef5bd8c6c0
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: nat-01847dc89797c93f4




  