AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CloudFormation Template to create VPC with Public and Private Subnets, IGW, Route Tables, and NAT Gateway.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CloudFormation Template to create IGW
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: MyIGW

AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS Cloudformation template to create AttachGateway
Resources:
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
