AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates VPC in us-east-1 region
  Author: Sadiya
  Company: test

Resources:
  MyCfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: MyVPC
        - Key: Env
          Value: Prod
        - Key: Department
          Value: DevOps

  MyCfnInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyIGW

  MyCfnAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-0522b23e14b1638de
      InternetGatewayId: igw-0124fbcbe44575b79

  MyCfnPublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0522b23e14b1638de
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: us-east-1d
      Tags: 
        - Key: Name
          Value: PublicSubnet  

   MyCfnPrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0522b23e14b1638de
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: us-east-1d
      Tags: 
        - Key: Name
          Value: PrivateSubnet 