name: continue update vpc demo
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: My input description
        required: false
        type: string
jobs:
  create-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
         
      - name: Continue Update Rollback
        run: aws cloudformation continue-update-rollback --stack-name prod-vpc

      - name: Wait for rollback to continue
        run: sleep 30
        
      - name: Describe Stack Events
        id: describe-events
        run: aws cloudformation describe-stack-events --stack-name prod-vpc
        
      - name: Print Stack Events for Debugging
        run: echo "${{ steps.describe-events.outputs.stack-events }}"
        
      - name: Describe Stack Status
        run: aws cloudformation describe-stacks --stack-name prod-vpc
        
      - name: Update Stack
        run: aws cloudformation update-stack --stack-name prod-vpc --template-body file://cloudformation/vpc.yaml
